name: 🚀 Deploy website on push

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  web-deploy:
    name: 🎉 Build, Rename, and Commit
    runs-on: ubuntu-latest

    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.17.0'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Rename the out folder to dalal
      run: mv out dalal

    - name: Commit the dalal folder
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Use the default GitHub token
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add dalal
        git commit -m "Auto-commit: rename and add dalal folder after build"
        git push origin production

  ftp-deploy:
    name: 🎉 FTP Deploy
    runs-on: ubuntu-latest
    needs: web-deploy
    steps:
    - name: 🚚 Get latest code with dalal folder
      uses: actions/checkout@v4

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp://217.21.94.151
        username: u251186022
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: /dalal/
        server-dir: /public_html/
        protocol: ftps
        port: 21
        log-level: standard

  cleanup:
    name: 🧹 Cleanup
    runs-on: ubuntu-latest
    needs: ftp-deploy
    steps:
    - name: Clean up build artifacts
      run: rm -rf dalal dalal.zip

    - name: Final cleanup (optional)
      if: always()
      run: |
        echo "Clean up done, no commit to repo."
