name: 🚀 Deploy website on push

on:
  push: # Deploy on push to the main branch
    branches:
      - main
  workflow_dispatch: # Enables the manual trigger

jobs:
  web-deploy:
    name: 🎉 Build, Commit, and Prepare Deployment
    runs-on: ubuntu-latest

    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.17.0'  # Ensure Node.js version meets your project's requirements

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Commit the out folder
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add out
        git commit -m "Auto-commit: add out folder after build"
        git push origin main

  ftp-deploy:
    name: 🎉 FTP Deploy
    runs-on: ubuntu-latest
    needs: web-deploy
    steps:
    - name: 🚚 Get latest code with out folder
      uses: actions/checkout@v4

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp://217.21.94.151
        username: u251186022
        password: ${{ secrets.FTP_PASSWORD }} # Store your FTP password as a secret in GitHub
        local-dir: ./out/ # Upload the contents of the out folder
        server-dir: /public_html/ # Must end with a trailing slash
        protocol: ftps # Use secure FTPS protocol
        port: 21
        log-level: standard

  cleanup:
    name: 🧹 Cleanup
    runs-on: ubuntu-latest
    needs: ftp-deploy
    steps:
    - name: Clean up build artifacts
      run: rm -rf out out.zip

    - name: Final cleanup (optional)
      if: always()
      run: |
        echo "Clean up done, no commit to repo."
