name: GWS to WordPress

on:
  workflow_dispatch: # This enables the manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.17.0'  # Ensure Node.js version meets your project's requirements

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Create ZIP of out folder
      run: zip -r out.zip out

    - name: Upload ZIP to FTP server
      run: |
        curl -T out.zip ftp://u251186022:${{ secrets.FTP_PASSWORD }}@217.21.94.151/public_html/out.zip --user u251186022:${{ secrets.FTP_PASSWORD }}

    - name: Extract ZIP on server via File Manager
      run: |
        curl -X POST https://srv784-files.hstgr.io/15bf51d26f35c315/files/public_html/extract.php \
        -F "file=@out.zip" \
        -F "destination=/public_html" \
        --user u251186022:${{ secrets.FTP_PASSWORD }}

    - name: Clean up
      run: rm -f out.zip

    - name: Final cleanup (optional)
      if: always()
      run: |
        echo "Clean up done, no commit to repo."
